name: 럭키

on:
  workflow_call:
    secrets:
      ANTHROPIC_API_KEY:
        required: true

jobs:
  lucky:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: 대상 레포지토리 체크아웃
        uses: actions/checkout@v4

      - name: 럭키 설정 가져오기
        uses: actions/checkout@v4
        with:
          repository: qodot/lucky
          path: .lucky
          sparse-checkout: |
            AGENTS.md

      - name: AGENTS.md 통합
        run: |
          if [ -f "AGENTS.md" ]; then
            mv AGENTS.md AGENTS.md.original
          fi

          cat .lucky/AGENTS.md > AGENTS.md

          if [ -f "AGENTS.md.original" ]; then
            echo "" >> AGENTS.md
            echo "---" >> AGENTS.md
            echo "" >> AGENTS.md
            cat AGENTS.md.original >> AGENTS.md
          fi

      - name: Claude Code 실행
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
